Javascript/javascript3/week1
Gohar33/hyf-homework pull request #11
Opened 2021-03-11 20:39 UTC by Gohar33

2021-03-22 20:18 UTC, aina21 requested changes
good job :)

2021-03-22 20:18 UTC, aina21 commented on javascript/javascript3/week1/giphy.js
> +const input1 = document.querySelector(".search")
Try to use meaningful names for variables.

2021-03-22 20:18 UTC, aina21 commented on javascript/javascript3/week1/giphy.js
> +        let inputVal = input1.value.trim()
const

2021-03-22 20:18 UTC, aina21 commented on javascript/javascript3/week1/giphy.js
> +        url = url.concat(inputVal)
why do you need to concat?

2021-03-22 20:18 UTC, aina21 commented on javascript/javascript3/week1/giphy.js
> +                let myDiv = document.getElementById("my-div")
const

2021-03-22 20:18 UTC, aina21 commented on javascript/javascript3/week1/giphy.js
> +                    let imgGif = document.createElement("img")
const

2021-03-22 20:18 UTC, aina21 commented on javascript/javascript3/week1/giphy.js
> +                    let imgGif = document.createElement("img")
Always use const until it won't let you :slightly_smiling_face:

2021-03-22 20:18 UTC, aina21 commented on javascript/javascript3/week1/homework.basic.js
> +const myFavoriteMusic = '{"name":"Favorite Music", "genres": [ "electronic", {"rock":["Russian", "Classic"]}, "classical"], "bands": ["DDD", "Pink Floyd", "Metallica"], "performers":["Zemfira", "Nils
this object should be in json file

2021-03-22 20:18 UTC, aina21 commented on javascript/javascript3/week1/weather.js
> +        let inputVal = input.value
const, and it's better to change a name to something meaningful.

2021-03-22 20:18 UTC, aina21 commented on javascript/javascript3/week1/weather.js
> +        let url = `http://api.openweathermap.org/data/2.5/weather?q=${inputVal}&units=metric&apikey=0284346df0317b81c2e17a35dfbda0c4`
same

2021-03-23 06:37 UTC, Gohar33 commented on javascript/javascript3/week1/weather.js
> +        let url = `http://api.openweathermap.org/data/2.5/weather?q=${inputVal}&units=metric&apikey=0284346df0317b81c2e17a35dfbda0c4`
Thank you Ida for your feedback, I'll implement this.

2021-03-23 18:22 UTC, merged