week4 homework
Gohar33/hyf-homework pull request #7
Opened 2021-02-11 17:15 UTC by Gohar33

2021-02-13 14:28 UTC, cameronjdavis requested changes

2021-02-13 14:28 UTC, cameronjdavis commented on javascript/javascript1/week4/index.js
> +                return number1 / number2;
What if the operator is not known? Can you add a `default` case to this switch statement to handle any math operator that is not known? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch

2021-02-13 14:28 UTC, cameronjdavis commented on javascript/javascript1/week4/index.js
> +        if (number1 && number2);
Does this line do anything? My guess is that it doesn't.

2021-02-13 18:02 UTC, Gohar33 commented on javascript/javascript1/week4/index.js
> +        if (number1 && number2);
Thanks Cameron, yes, you're right, I forgot to delete it while testing few options.

2021-02-13 18:04 UTC, Gohar33 commented on javascript/javascript1/week4/index.js
> +                return number1 / number2;
But if the operator is unknown how can I know which kind of action I should assign to it? I can add a default but I don't know which mathematical calculations I should assign?

2021-02-14 19:14 UTC, merged

2021-02-15 13:09 UTC, cameronjdavis commented on javascript/javascript1/week4/index.js
> +                return number1 / number2;
True, you don't know how to handle an unknown operator but the user could enter an unknown operator. You should add a `default` option to tell the user that you can't handle the unknown operator.

2021-02-15 15:09 UTC, Gohar33 commented on javascript/javascript1/week4/index.js
> +                return number1 / number2;
Oh great, I did exactly that in the feedback implementation, just added default and returned "Error". Thanks for the feedback and for pushing us to think about more options, that's very informative and helpful :)